{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.huolala.asm_plugin",
    "module": "asm",
    "version": "1.2.5.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asm-1.2.5.3-SNAPSHOT.jar",
          "url": "asm-1.2.5.3-SNAPSHOT.jar",
          "size": 13295,
          "sha512": "213c929a2b2d0e7a55943f8ae941d6b2ef7b4eb31fb8850699f4cd24b7e37bb6c397d64efcb7ed0c9221c29d4d7d2a200c38ad3db9aac7ed3fc939efe372761c",
          "sha256": "4b311a98a8017fff2320a732abd93f77cacc1dd80100c86423e98f2d137a04e8",
          "sha1": "4133919ed16c8c5ba34f4dce4e0b8e1515356a1e",
          "md5": "a7f61653433690e533eb81c12c065158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "asm-1.2.5.3-SNAPSHOT.jar",
          "url": "asm-1.2.5.3-SNAPSHOT.jar",
          "size": 13295,
          "sha512": "213c929a2b2d0e7a55943f8ae941d6b2ef7b4eb31fb8850699f4cd24b7e37bb6c397d64efcb7ed0c9221c29d4d7d2a200c38ad3db9aac7ed3fc939efe372761c",
          "sha256": "4b311a98a8017fff2320a732abd93f77cacc1dd80100c86423e98f2d137a04e8",
          "sha1": "4133919ed16c8c5ba34f4dce4e0b8e1515356a1e",
          "md5": "a7f61653433690e533eb81c12c065158"
        }
      ]
    }
  ]
}
